spring:
  datasource:
    url:
    username:
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate:
      show_sql: true
      format_sql: true
      hbm2ddl.auto: validate


  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
            scope:
              - email
              - profile
#          github:
#            client-id: ''
#            client-secret: ''
#            scope:
#              - user:email
#              - read:user

telegram:
  bot:
    username:
    token:
    channelChatId:

  mail:
    host:
    port:
    username:
    password:
    properties:
      mail:
        smtp.auth: true
        starttls.enable: true

