spring:
  datasource:
    url:
    username:
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate:
      show_sql: true
      format_sql: true
      hbm2ddl.auto: validate

  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:

  mail:
    host: smtp.yandex.ru
    port: 465
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          starttls:
            enable: true

telegram:
  bot:
    username:
    token:
    channelChatId:



